###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no

# Used for permalinks
_site_url: http://draft.high90.pub/

# Enter your license key
_license_key: 41725cad-495d-4a07-9499-2369b7d4e012
